version: "0.2"
language: en
words:
  - airules
  - antfu
  - autohide
  - catppuccin
  - checkpointing
  - clmv
  - daltonized
  - devbox
  - ghostty
  - HISTFILE
  - HISTSIZE
  - largesize
  - launchanim
  - mineffect
  - mkcd
  - naito
  - naitokosuke
  - nixfmt
  - nixpkgs
  - Notif
  - numtide
  - Pathbar
  - pkgs
  - promptinit
  - recents
  - RPROMPT
  - SAVEHIST
  - screencapture
  - setopt
  - superfile
  - swipescrolldirection
  - tilesize
  - treefmt
  - zhaofengli
ignorePaths:
  - node_modules
  - .git
  - "*.lock"
  - result
  - flake.lock
  - ___naito___/
